const mongoose=require('mongoose')
const UserSchema=new mongoose.Schema({
    Firstname:{
        type:String,
    },
    Lastname:{
        type:String,
    },
    Email:{
        type:String
    },
    isAdmin:{
        type:Boolean,
        default:false
    },
    DateofBirth:{
        type:Date,
        default:''
    },
    Password:{
        type:String
    },
    Followers:{
        type:Array
    },
    Followings:{
        type:Array
    },
    Aboutme:{
        type:String,
        default:undefined
    },
    City:{
        type:String,
        default:undefined
    },
    Relation:{
        type:String,
        default:undefined
    },
    Profilepic:{
        type:String
    },
    Coverpic:{
        tye:String
    },
    userid:{
        type:String
    }
},{timestamps:true})
const Userdb=mongoose.model('user',UserSchema)
module.exports = Userdb